table_not_found = {'error':'table not found'}
supply_command = {'error':'supply a command'}
provide_auth = {'error':'you must provide both a username and a password'}
wait_your_damn_turn = {'error':'it\'s not your turn'}
wait_your_damn_turn = {'error':'you must supply a command'}
join_the_game = {'error':'you are not in this game'}
cant_hit = {'error':'you cannot hit this turn (is it your turn?)'}
cant_double_down = {'error':'you cannot double down this turn (is it your turn? do you have more than 2 cards?)'}
cant_bet_placed = {'error':'bets have already been placed'}
cant_bet_amount = {'error':'you cannot bet more money than you have'}
cant_bet_below_minimum = {'error':'you must bet at least the table minimum. If you do not have enough, then bet all of your money'}
cant_stay = {'error':'you cannot stay this turn (is it your turn?)'}
cmds_locked_bets={'error': 'commands currently locked, autbetting lagging players'}
success_table_started={'success':'you have 10 seconds to place bets'}
game_in_progress_join={'error': 'you cannot join a game in progress'}
table_status_codes={0:'not_started', 1:'betting', 2:'playing', 3:'between rounds', 4:'game over'}
dealer_status_codes={0:'not_stayed', 1:'stayed'}
player_status_codes={0:'waiting for start', 1:'betting', 2:'currently turn', 3:'not turn', 4:'stayed', 5:'out', 6:'busted', 7:'doubled_down', 8:'won'}
card_suits=['H','S','D','C']
card_vals=['2','3','4','5','6','7','8','9','10','J','Q','K','A']